environment:
  DATABASE_URL: ${DATABASE_URL}
packages:
  - name: sample
    actions:
      - name: hello
        runtime: "python:default"
        limits:
          timeout: 15000
          memory: 1024
