packages:
  - name: sample
    environment:
      DATABASE_URL: ${DATABASE_URL}
    functions:
      - name: hello
        runtime: python:default
        limits:
          timeout: 15000
          memory: 1024
